### ISSUE TITLE
Make compatible with Orbital Decay

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1032]
So, Orbital Decay was updated:
https://forum.kerbalspaceprogram.com/index.php?/topic/175618-14x-orbital-decay-resumed-v1611-04-jun-2018/

This has to be avoided:

> Mechjeb autopilot can fail when nearly reaching a set altitude due to drag reducing the actual altitude - Fix in 1.6.0, other autopilot mods may be effected. 

The "Fix in 1.6.0" was written by the original dev, but it never happened.
It's not clear if the fix has to be done on that side or on this side...

This occurs:
```
MechJeb module MechJebModuleAttitudeController threw an exception in OnFixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at MuMech.MechJebModuleAttitudeController.attitudeGetReferenceRotation (AttitudeReference reference) [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleAttitudeController.attitudeAngleFromTarget () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebModuleAttitudeController.OnFixedUpdate () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.FixedUpdate () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

```

**Comment by lamont-granquist** [comment]
probably gonna have to have someone that uses Orbital Decay track that down.

that stack trace isn't all that useful other than whatever the target was set to has some object it needs disappearing.

i suspect the description is wrong since moving the ship around isn't going to affect the attitude controller.  looks more like the target or node or something disappeared prematurely, and i'd suspect orbital decay is more likely to be buggy.  adding piles of Debug.Log statements to track down which object is NRE'ing would probably determine the culprit.

**Comment by PapaJoesSoup** [comment]
Agreed.  There is still some work to clean up the existing cod and to eliminate some garbage entries in the log.   I got rid of some, but there are more to track down.  Also SolarCycleSimulator has some log spamming.  working on those.

**Comment by lamont-granquist** [comment]
closing until there's a better diagnosis of something MechJeb could do better (please open a new issue if some concrete ideas come up).
