### ISSUE TITLE
missing options

### ISSUE THREAD

**Issue by apholis** [MuMech/MechJeb2#1043]
played in career and sandbox and it only gives a few options, in career i had everything unlock and still missing, and in sandbox it's missing them now as well.

**Comment by lamont-granquist** [comment]
This issue is being closed because it seems to be a question more suited to ask the community.  This issue tracker is for tracking bugs and feature requests.  The forum thread is an excellent place to ask for help:

https://forum.kerbalspaceprogram.com/index.php?/topic/154834-14x-anatid-robotics-mumech-mechjeb-autopilot-274-23-september-2018/

There are also KSP discords and IRC channels which may be better to ask for support
