### ISSUE TITLE
Ascent guidance set to 0° inc = no inc change on ascent

### ISSUE THREAD

**Issue by Gordon-Dry** [MuMech/MechJeb2#1046]
When another value than 0° is set as inclination in Ascent Guidance, then some correction occurs during ascent.
If it's set to 0°, the first try/attempt of correction occurs on circularization ...

**Comment by lamont-granquist** [comment]
If you're talking about launches to inclinations below your launch latitude using the classic ascent algorithm, then this isn't a bug -- or at least not a bug that will ever get fixed.  Those kinds of launches are very expensive in terms of dV and should mostly be avoided.  If you need to do that you should launch to the inclination that matches your current latitude, and then execute a plane change at the next AN/DN.  There is not a lot of cost savings in trying to launch directly to that orbit compared to doing a launch and a plane change.  Most of those trajectories (that aren't too small to matter) will wind up looking like that anyway and will require an optimized coast to the equator to do a plane change.

**Comment by Gordon-Dry** [comment]
@lamont-granquist Thank you for the reply.

Btw I have a "simple" question:
Are you actual builds only destined to be used when RO/RSS is installed or can they also be used when "only" RSS is installed and no RealFuels, too?
Like "Shuttle PEG Release #17 KSP 1.4.x"
I'm not quite sure about that ...

**Comment by lamont-granquist** [comment]
note though that I didn't ever merge PEG to core, because there is that small angle approximation and its very difficult to explain to game players when you hit it what its doing and how to avoid it -- you can even encounter that on launches in RSS.

If you see:

tgo 41.0s
phi  45.00

Then you're not going to space.  The phi value MUST start counting down from 45 degrees before tgo is 40 seconds.  What is additionally confusing is that once you're below 40 seconds then phi always counts down to zero.  So the trick is to look for when phi starts counting down from 45, and if its > 40 seconds you're okay.  If not, you won't wind up where you planned, in a very confusing way.

I actually ping'd the author of a better implementation which is what the shuttle uses, which gets rid of that nonsense, but haven't heard back from CSDL as to if they can release it publicly.

**Comment by lamont-granquist** [comment]
Yeah, in this case I keep trying to explain it to people on slack/discord/irc and failing, so if I can't explain it, I can't really document it.  It boils down to "NASA doesn't have this problem because they have real trajectory optimizers, and you're much worse at rocket trajectories than you think you are -- get gud and stop asking the algorithm to do things it wasn't designed for..."  which results in "but i want magicsauce button to press and not have to think...."

As a result though I am working on a real trajectory optimizer though, but it is not ready for prime time....
