### ISSUE TITLE
compensating for ullage with RF

### ISSUE THREAD

**Issue by Commissar0617** [MuMech/MechJeb2#1073]
MJ n3eeds to work with ullage for realfuels. according to starwaster, it did so for a short time in the past, but apparently, that was broken. causes serious problems, and this is a very popular mod.

**Comment by lamont-granquist** [comment]
It does.  Under utilities there are two options.  One is for "use RCS to ullage" (which is pretty much safe to always use and should be the default), and the other one is "prevent unstable ignitions" which is off by default.  The only problem with the latter option is that it is very strict and sometimes with sounding rockets it is better to fire with a less than stable ignition state and risk it since you can't ever ullage up the sounding rocket more than it currently is.  Once a career is past the sounding rocket stage that option should probably be ticked by the user (auto detecting and being perfectly smart about the setting is going to get complicated)

There's an existing bug where when autostaging to a stage with unstable ullage you will burn an ignition due to a one-KSP-tick race condition that has been fixed in a dev branch of mine.  I think practically that only affects PEG coast stages and those were experimental anyway, the PVG overhaul will fix all of that.

So unless there's a specific bug report not covered by all that I think I'm going to close this...

**Comment by Commissar0617** [comment]
it's not though. it's attempting the engine first, and then using rcs until i switch the engine off and on. both options are selected.

**Comment by Commissar0617** [comment]
(second post because github is dumb with waterfox). i've observed this with multiple rockets, in the 50-300t range, so we're not talking sounding rockets.

**Comment by lamont-granquist** [comment]
I just tested it and it worked fine.  I don't know and can't guess what you're doing differently.

**Comment by Commissar0617** [comment]
huh. im not doing anything different. i know it's worked in the past.

**Comment by lamont-granquist** [comment]
i haven't touched it in quite some time, nothing has changed afaik.

**Comment by lamont-granquist** [comment]
#1078 is the fix for the only outstanding ullage issue i'm aware of, that is in build 823: https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/823/

**Comment by lamont-granquist** [comment]
yeah, i'm completely unable to replicate this.  i thought i had a replication case, but it was just that the J-2 motor needs eC to fire and i forgot to pack any batteries so did it to myself.  other than that its been working fine.

note that in the atmosphere if you stage early and low then you'll get hit with enough dynamic pressure to instantly "de ullage" your upper stage and RCS will be unable to cope with that (and in some cases I've found sep motors don't burn long enough to ullage it back up).  need to use hot staging for that (and autohotstaging support got merged in this weekend).
