### ISSUE TITLE
Porkchop stuck creating node (if optimizer crashes due to outgoing Moon/Mun encounters, user needs feedback)

### ISSUE THREAD

**Issue by mpredosin** [MuMech/MechJeb2#1086]
I'm trying to have mechjeb create a node from the porkchop selection.  It usually works fine, but now I'm trying to transfer to Jool.  Using lowest or manually picking a point on the graph causes mechjeb to get stuck when creating the node.   It seems ASAP is the only way to keep it from getting stuck.  I also found that switching to limited time also works.

**Comment by lamont-granquist** [comment]
What version of MJ?

**Comment by lamont-granquist** [comment]
It may be that you're getting a Mun encounter on the way out of Kerbin.  Although I don't think the UI gives you back enough information to show that.

**Comment by mpredosin** [comment]
MechJeb 2 v2.8.1

**Comment by mpredosin** [comment]
If you need logs or backtrace let me know.  I'm not familiar with KSP modding.  But, I'm happy to provide any info you need.

**Comment by lamont-granquist** [comment]
Step 1 is probably detecting issues with outgoing Moon/Mun encounters and logging details to KSP.log and/or displaying information to the user.  My guess is that is what is going on, but without logging one way or the other it is impossible to prove it.

**Comment by aequasi** [comment]
Also dealing with this in 2.9.2.0. Not sure if it's related to Mun though? I'm also trying to get to Jool

**Comment by lamont-granquist** [comment]
The fixes that went into the advanced transfer planner after 2.9.2.0 may have fixed this.

Those are only available via the dev builds on 1.8/1.9 right now:

https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/

There's no good reproduction steps here so I can't say specifically what the bug was or if it really got addressed, but in particular the old code was absolute crap for anything other than a near-circular parking orbit (how close to near circular?  dunno).

Gonna declare bankruptcy on this issue though on the assumption that the issue probably got addressed.

If there's still issues:

1.  ensure running on a post-2.9.2.0 version that has the tickbox for planning the circularization burn at the target planet.

2.  open a new issue.

3.  include the relevant logs (there's a lot more logging from the advanced transfer planner now).

4.  include the UT of the transfer and which planets it is between so that the configuration of the solar system can be replicated.

5.  include the keplerian elements of the parking orbit (ideally all six so that the parking orbit can be fully replicated as well).
