### ISSUE TITLE
[Suggestion] Autothrottle

### ISSUE THREAD

**Issue by Monniasza** [MuMech/MechJeb2#1177]
## MechJeb Version
(Not necessary, just a suggestion)

## KSP Version
(Not necessary, just a suggestion)
## Description
Add autothrottle function, which takes TWR and aerodynamic drag into account.

It will look like this:
╔════════[x]
║Autothrottle ║
║═══╪════║
╚════════╝

## Replication Case
(Not necessary, just a suggestion)

## KSP.log
(Not necessary, just a suggestion)

**Comment by lamont-granquist** [comment]
There's already the max Q limiter on the throttle.

Since the pre-1.0 soup has gone away there's also very little need to do this.  There are no intermediate thrust curves for orbital class rockets and drag is less important than utilizing high TWR, so throttle should always be full.  And the structural effects of dynamic pressure aren't modeled at all, so there's no need to throttle down during maxQ like real rockets do.
