### ISSUE TITLE
Spam NRE in editor

### ISSUE THREAD

**Issue by thghca** [MuMech/MechJeb2#1185]
## MechJeb Version
2.8.3.0-894

## KSP Version
1.7.3

## Description
This line spams NRE in editor:
https://github.com/MuMech/MechJeb2/blob/23e2661868d0fd23e98d0085a9d7c53c225a0a78/MechJeb2/MechJebModuleMenu.cs#L342

## Replication Case
Mechjeb unlocked from start with MechJebUnlocked.
Upgrade ksc to use maneur nodes, enter editor, add part with mechjeb.

## KSP.log
spams this:
[EXC 18:52:07.045] NullReferenceException: Object reference not set to an instance of an object
	MuMech.MechJebModuleMenu.<SetupToolBarButtons>b__30_4 ()
	MuMech.MechJebModuleMenu+<>c__DisplayClass31_0.<CreateFeatureButton>b__0 ()
	MuMech.MechJebModuleMenu.OnMenuUpdate ()
	MuMech.MechJebCore.Update ()

**Comment by lamont-granquist** [comment]
problem looks like `core.node.enabled` is true which shouldn't ever happen in the editor.  something left the maneuver node executor turned on.

**Comment by pmborg** [comment]
Hum... I have also this bug,
This is so annoying I get 150 messages of this per second, the same as FPS...., the all system become slower because of this.
And is very simple to replicate I just need to pick up any command module.
"Mk2 Command Pod", please let me know if you need my log file.

But basically is thousands of this:
[EXC 18:44:16.876] NullReferenceException: Object reference not set to an instance of an object
        MuMech.MechJebModuleMenu.<SetupToolBarButtons>b__30_4 () (at <2e230d4e49354a07858a9faa52799159>:0)
        MuMech.MechJebModuleMenu+<>c__DisplayClass31_0.<CreateFeatureButton>b__0 () (at <2e230d4e49354a07858a9faa52799159>:0)
        MuMech.MechJebModuleMenu.OnMenuUpdate () (at <2e230d4e49354a07858a9faa52799159>:0)
        MuMech.MechJebCore.Update () (at <2e230d4e49354a07858a9faa52799159>:0)

**Comment by lamont-granquist** [comment]
Fixed in 2.9.1:

https://forum.kerbalspaceprogram.com/index.php?/topic/154834-18x-anatid-robotics-mumech-mechjeb-autopilot-291-15-november-2019/page/111/&tab=comments#comment-3711626
