### ISSUE TITLE
feature request: Propeller Pitch control

### ISSUE THREAD

**Issue by Ruedii** [MuMech/MechJeb2#1197]
This is a feature request:
Propeller auto-pitch

I noticed someone requesting a mod to get auto-pitch-control for the breaking ground propellers added in a mod.  I thought immediately that this was both within the capability and scope of MechJeb. 

It should adjust based on airspeed (obviously) and have a tuning value (preferably in a slider) for limiting the torquing tendency on planes at the expense of thrust.

**Comment by lamont-granquist** [comment]
Its not a bad idea, but it would have to be done as an external contribution and PR, there's no plans right now to do this (and way too vast of a backlog in this mod because the scope is already too vast)

**Comment by DBooots** [comment]
@Ruedii I'm developing this as a standalone mod and just stumbled across this. I've got all the math worked out for the analytical solution and now I'm just working on implementing it into KSP.

@lamont-granquist Once I'm done, would you also like a PR (or even just the math methods) or would you leave it out of MechJeb since it would be more-or-less feature-complete in standalone?
