### ISSUE TITLE
Duna auto landing is not working

### ISSUE THREAD

**Issue by sokakpiskopati** [MuMech/MechJeb2#122]
Hi,
I tried to land on my target with mechjeb but it didn't work it burned wrong way.

**Comment by jonathankoren** [comment]
This problem persists. I'm getting projected landing points that jump wildly on either side of the target point. If parachutes deploy, it consistently misses the mark by landing well short.

A near vertical approach from starting in an orbit well past Ike will work. But flying through the atmosphere from an initial orbit of 60 km will exhibit this broken behavior. It's super annoying, because autoland is pretty much the only way I can rendezvous on the surface.

**Comment by lamont-granquist** [comment]
closing for #1052
