### ISSUE TITLE
Problem with the bi-impulsive (Hohmann) transfer to target

### ISSUE THREAD

**Issue by Octonath** [MuMech/MechJeb2#1230]
I use MechJeb2 2.9.1.0 and KSP 1.8.1.2694 The problems that is when i do a bi-impulsive (Hohmann) transfer to target (the mun in the planner that do a direct flight to the mun and not an apoapsis or periapsis so i can't orbit around the mun. Can't you help me ?
![Kerbal Space Program Screenshot 2020 02 02 - 09 57 00 60](https://user-images.githubusercontent.com/47495624/73605792-ebb8d980-45a2-11ea-9688-629f7f3966c0.png)
![Kerbal Space Program Screenshot 2020 02 02 - 09 57 09 80](https://user-images.githubusercontent.com/47495624/73605793-ebb8d980-45a2-11ea-9b41-8bcb857120b4.png)

**Comment by lamont-granquist** [comment]
There's no function to select the periapsis distance.  Implementing that correctly will take months of work, it isn't simple.  For now you can either manually adjust it with the node editor, or else use the "fine tune closest approach to target" (which is also somewhat inaccurate, because the problem is hard).

**Comment by lamont-granquist** [comment]
dup of #1060 i think (or one of the other epics)
