### ISSUE TITLE
throttle was twitching after using AscentAutopilot

### ISSUE THREAD

**Issue by Kituro912** [MuMech/MechJeb2#1308]
## MechJeb Version
v2.9.2

## KSP Version
v1.8.1.2694

## Description
I'm an RSS/RO(uses Principia)player, after I used the AscentAutopilot(PVG mode) ,when the vessel was in the orbit(the launch has finished and I pressed the "Disengage autopilot" on the AscentAutopilot), I press "Z" key to increase the throttle to 100% so that I wanted to execute a maneuver, but the throttle began to twitch between 0% and 100% crazily, it moved too fast to see the throttle clearly on the monitor. My engines iginition times was decrease to 0 fleetingly.I have tested servel vessels and the "dev" version of MechJeb2, they have the same problem. The video of this problem was in the attachments.
Hope you will fix it!

## Replication Case

[video.zip](https://github.com/MuMech/MechJeb2/files/4870246/video.zip)
[mechjeb_settings_type_CommPionner - 2.txt](https://github.com/MuMech/MechJeb2/files/4870250/mechjeb_settings_type_CommPionner.-.2.txt)
![Snipaste_2020-07-03_22-34-08](https://user-images.githubusercontent.com/61297959/86479462-cf51e080-bd7e-11ea-999d-7fb73c1816cb.jpg)

## KSP.log
[KSP.log](https://github.com/MuMech/MechJeb2/files/4870234/KSP.log)

**Comment by lamont-granquist** [comment]
You haven't really included the right information to determine what is going on.  Since you've disabled the ascent autopilot nothing involved in the Ascent likely has anything to do with the issue at all.  The fact that you're using Principia is interesting, but you haven't included which version of Principia, you should consider making sure to track the latest Principia version since it has been having some strange bugs.  The KSP.log file that you have included doesn't have anything in it either, it looks truncated or the wrong file.  There are logs from the throttle controller which should be included in the correct KSP.log file which happen when the vessel is being ullaged which could be useful if you can find them.  What would also be more useful than the Ascent settings is if "use RCS for ullage" and/or "prevent unstable ignitions" are checked, since those are the settings used by the throttle controller.  Most useful would probably be the vessel so I could just launch it and replicate.

**Comment by lamont-granquist** [comment]
Closing due to lack of response
