### ISSUE TITLE
All windows locked to top left

### ISSUE THREAD

**Issue by nonya0992** [MuMech/MechJeb2#1467]
All my mecjeb windows are locked to the top left of the window. When I move them anywhere else and release them the windows move back to the top left.

**Comment by nonya0992** [comment]
Recently re-downloaded the game and this mod.

**Comment by arch-linux** [comment]
I am as well having this exact issue, with the latest update of the game mechjeb is stuck glued to the top left-hand-top corner of the screen interfering with the time settings and is unable to be moved.

**Comment by sarbian** [comment]
As stated in the issue template we need  you to share a log to actually find the source of the problem

**Comment by FazerFox** [comment]
i am also having this issue it locks the mechjeb tab to the top left of my screen here's my log
[KSP.log](https://github.com/MuMech/MechJeb2/files/6766413/KSP.log)

**Comment by FazerFox** [comment]
here is a screenshot of what it does

![image](https://user-images.githubusercontent.com/60765508/124522554-97470880-ddeb-11eb-9a52-d912499ee96f.png)

**Comment by FazerFox** [comment]
A temporary fix is to just spam click random menus until they move back in place

**Comment by GooUckd** [comment]
Same issue. 

> A temporary fix is to just click settings and it goes back into place

When I do that the stuff is still at the left top corner but the MechJeb button isnt.

**Comment by GooUckd** [comment]
![image](https://user-images.githubusercontent.com/62660100/124957073-59332a00-e021-11eb-8989-7a8e5763bd4d.png)
This is also what the menus have become.

**Comment by GooUckd** [comment]
> here is a screenshot of what it does any of the menus go off screen
> 
> ![image](https://user-images.githubusercontent.com/60765508/124522554-97470880-ddeb-11eb-9a52-d912499ee96f.png)
> 
> it also says incompatible with the newest version of KSP
> 
> ![image](https://user-images.githubusercontent.com/60765508/124522828-77fcab00-ddec-11eb-8434-67292c5932eb.png)

I think that MechJeb is incompatible with multiplayer mods after 1.12. Need's fixing I guess. (I am using Luna)

**Comment by GooUckd** [comment]
..but my best guess is that MechJeb hasn't updated and maybe 1.12 did some display stuff idk

**Comment by DucatiLove** [comment]
Same problem. Anyone have a solution?

**Comment by samche2000** [comment]
Same problem, logs inside
[KSP.log](https://github.com/MuMech/MechJeb2/files/7120149/KSP.log)
[MMPatch.log](https://github.com/MuMech/MechJeb2/files/7120151/MMPatch.log)
[ModuleManager.log](https://github.com/MuMech/MechJeb2/files/7120152/ModuleManager.log)

**Comment by sarbian** [comment]
You have other mods (mainly ClickThroughBlocker that create problems in MJ). I can not fix it.

**Comment by GooUckd** [comment]
> You have other mods (mainly ClickThroughBlocker that create problems in MJ). I can not fix it.

Oh... What kind of problems may I ask?
(Just curious, I won't be playing KSP until KSP 2 is released.)

**Comment by sarbian** [comment]
Mods not built for the current KSP engine version generate error when other mods use reflection to find dynamic modules, like MK do. I could add more protection again this but the real problem is the other mod.
Like this:

`[ERR 10:21:30.416] MechJeb moduleRegistry creation threw an exception in LoadComputerModules loading ClickThroughBlocker, Version=0.1.10.17, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
  at MuMech.MechJebCore.LoadComputerModules () [0x0002d] in <84399c37aa054a3da1259664708ceb74>:0 
`

**Comment by GooUckd** [comment]
> Mods not built for the current KSP engine version generate error when other mods use reflection to find dynamic modules, like MJ do. I could add more protection again this but the real problem is the other mod. Like this:
> 
> `[ERR 10:21:30.416] MechJeb moduleRegistry creation threw an exception in LoadComputerModules loading ClickThroughBlocker, Version=0.1.10.17, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown. at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool) at System.Reflection.Assembly.GetTypes () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 at MuMech.MechJebCore.LoadComputerModules () [0x0002d] in <84399c37aa054a3da1259664708ceb74>:0 `

You could probably contact the creator of click through blocker. They might help. (Sorry for not responding, gmail didn't send notifications)

**Comment by DjSteveOhh** [comment]
i installed kerbal engineer which has a screen in same location as the mechjeb button , now mechjeb button is at top left location of the screen ( like screen shot above ) and when you click an item , the new screen is placed offscreen in top left corner... you can drag the new screen on stage but when you let it go it moves back to the top left corner.  i removed kerbal engineer mod but MJ button stay's in corner..
In which cfg file are the locations of them screens and MJ button stored ??

**Comment by ChickenLentilSoup** [comment]
My MechJeb windows do not save their location or inputted data. I have the same problem where at first everything is locked to top left corner,
<img width="960" alt="image" src="https://user-images.githubusercontent.com/119046212/203976040-9a5a678c-dc42-4fa8-b5ad-18b1c34eca11.png">
until I press the settings button and the window pops to the right.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/119046212/203976159-6b7d98c2-7fb5-46a7-8d31-94fc295baa82.png">
Additionally I can not access the actual settings menu because it is stuck on the top left corner.
<img width="963" alt="image" src="https://user-images.githubusercontent.com/119046212/203976267-771d5ce4-6c4f-441e-950f-813af1a30377.png">
Also, if anyone has any idea on why my Kerbal's face cams are black, fixes would be appreciated.

**I checked the MechJeb2 files and I noticed there was no PluginData folder when I close the game, so there is no where the game is saving the positions of the windows and which one's I have open.** 
I have uninstalled Kronometer as suggested and nothing changed. I noticed this bit in the log files (It repeats hundreds of times):
"[LOG 22:23:21.415] [MechJeb2] Loading Mechjeb 2.14.1
[ERR 22:23:21.421] MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:"

What should I do?
Log File: [KSP.zip](https://github.com/MuMech/MechJeb2/files/10092388/KSP.zip)

**Comment by ScopeCZ** [comment]
In moment u active MJ settings, minimize MJ by LMB, then click And hold RMB to move it to sides on top edge (other MJ Windows also movable by RMB when settings active, but theyre not docked).

**Comment by sarbian** [comment]
>What should I do?

The interesting part of the log you quoted is 1 line further:
```
[LOG 22:23:21.415] [MechJeb2] Loading Mechjeb 2.14.1
[ERR 22:23:21.421] MechJeb caught a ReflectionTypeLoadException. Those DLL are not built for this KSP version:"

[ERR 22:20:06.295] FMRS 1.0.1.0 GameData\FMRS\FMRS.dll

```
The FMRS version you use is **old** (2015). There have been countless update of that mod by LGG: https://github.com/linuxgurugamer/FMRS/releases
And your log is filled with errors from other missing or breaking mods. Sorry, but I can not do any kind of support for install that are (from my point of view) broken.

Use CKAN to install mods. At least you should end up with mods versions that are compatible with the current KSP version.
