### ISSUE TITLE
MechJeb 2's menu handle is stuck on the left hand corner

### ISSUE THREAD

**Issue by KommandantGalileo** [MuMech/MechJeb2#1566]
I have updated to the newest version, this is still happening
[KSP.log](https://github.com/MuMech/MechJeb2/files/9039054/KSP.log)

**Comment by KommandantGalileo** [comment]
so Kronometer is causing these problems?

**Comment by sarbian** [comment]
Try without it and see.

**Comment by KommandantGalileo** [comment]
I'll respond after testing

**Comment by weadmebe** [comment]
i dont have kronometer and this problem is still happening after i uninstalled KCT and ohscrap how do i fix it?

**Comment by darrencubitt** [comment]
Make sure ModuleManager is up to date. I had the same problem and this fixed it.

**Comment by Bazmann44** [comment]
I have the same exact problem. Is there anything i can do about it ? 
Mechjeb is in the upper left corner and it will stuck their. If i want to drag the windows in the middle its not working.
Thanks for your help.
[KSP.log](https://github.com/MuMech/MechJeb2/files/9221598/KSP.log)
If you need more information pleas let me know :) I also hope that log file is correct im not sure to be honest.

**Comment by AlonzoTG** [comment]
Mee tooo!!  I have a modpack that I've been using since 2014 or so. Game plays and is smooth but yeah, it is possible to drag the mechjeb windows but they are always reset to position 0,0 every few milliseconds. Only other issue with my install right now is that tweakscale threw a hissy fit, caused everything to crash and burn and had to be uninstalled. Extraplanetary launchpads seems to be having similar issues but ground construction seems to be good.

**Comment by AlonzoTG** [comment]
update Module manager 4.2.2 seems to have fixed it.

**Comment by anthonyjolson87** [comment]
I found it was the AntennaHelper and Kronometer mods that were causing the MechJeb menu to lock to the upper left AND the causing the settings and rover autopilot windows to be disabled.  They also caused problems with window persistence
