### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Sinomen** [MuMech/MechJeb2#1691]
@lamont-granquist 

Couple of things aren't working properly anymore since the recent updates, from ascend PVG to executing man. nodes.

Please contact me directly.

**Comment by Bitgedon** [comment]
Second this. I'm technically not using PVG as it's intended but also it's throwing really really dumb errors. Like saying it's finished while it's still on the pad. Or complaining the thrust is off while it doesn't attempt to turn on the engines.

Will also sometimes throw converged optimizer iteration fails during completely average flights seemingly at random, most of the time it will resolve itself but sometimes it doesn't

**Comment by Sinomen** [comment]
@lamont-granquist 

I understand that MJ Dev is kind of a playground for you, Which is more than totally fine, imo. Hey, it is clearly stated that the the Dev version may have issues, no doubt about that. If you don't like to deal with these, use the non-Dev version. So far, so good.

My issue here: people are installing and using the Dev versions, for good reasons. We, the users, are dependent on you, the developers. And as much as I'm fine with MJ Dev being your playground, we, the users, depend on your work. 
And we do report issues, bugs. Those reports though do not seem to get much attention recently. E.g. it took more than a month to fix that simple bug regarding the no more working Asparagus Staging. It worked fine in #1155, got broken in #1156. A simple issue caused by a comparison operator that has been forgotten to be changed. These things do happen, no biggie.
But why did it takke more than a month to fix this? To change a simple comparison operator?

Now I do have issues with PVG during ascent, some rockets tend to do an oscillating roll movement with the amplitudes increasing with each period. New issue, was fine before.

I mean, what can ordinary users like me do but notify you, the developers, of such issues/bugs? As I said, your playground, totally fine. 

But please, keep in mind, that others actually do depend on your work. Ok?

Thanks for your time reading this.

Kind regards

Sinomen

**Comment by Bitgedon** [comment]
Sir/Ma'am first I don't think it's a good idea to @ who I assume is one of the devs (idk who is who, I openly admit I don't use github often because I have no idea how to code) second, the indev versions are unstable, because it's in dev. Third, devs have lives, they can't constantly be fixing things as soon as they pop up. Fourth, less roll authority, that's entirely a you problem. Fifth, if you need the issue fixed so badly, find out how to fix it yourself and make a pull request. 

and to whoever comes to resolve this thread I swear I don't know the person above me I just didn't want to waste space and open a separate issue for something I thought was already here.

**Comment by Bitgedon** [comment]
Hiding my previous messages since I'm slowly figuring out my issues with PVG were my fault. I haven't worked all of them out but most I've been able to work around with some funky manipulation of the ascent settings. Sorry for the bother.
