### ISSUE TITLE
Gravity losses error

### ISSUE THREAD

**Issue by futrtrubl** [MuMech/MechJeb2#190]
MechJeb shows gravity losses increasing even when engines not firing. To reproduce go into an eccentric orbit, after periapsis as you gain altitude and orbital speed decreases it counts that decrease as gravity losses. It doesn't seem to take into account gravitational potential gains.
Probably best to only base this stat on thrust vector and gravity vector.  Formula to use based on http://ganeff.com/astrodynamics-knowledgebase/olfar/4-celestial-mechanics/gravity-losses/ seems to be (time interval \* gravity \* sinɤ) where ɤ is the angle from the plane that is normal to the gravity vector to the thrust vector or more simply angle between thrust and gravity vectors -90 degrees. Not sure how to handle negative ɤs or thrust less than gravity.

**Comment by lamont-granquist** [comment]
This has been mostly fixed, but its waiting on a patch in my branch to land to actually turn off gravity losses with zero thrust.

**Comment by lamont-granquist** [comment]
#1797 gravity loss runs constantly, which is correct (because gravity runs constantly).

**Comment by futrtrubl** [comment]
It's not when the gravity loss calculation runs that's the problem, it's the calculation itself that is wrong. That there are no gravity losses when there is no thrust is the example and proof.
Gravity losses is the deltaV lost to counteracting gravity. Think of a stationary vehicle thrusting up at 1g in a 1g field. All that thrust goes into just maintaining its position and is lost, not converted to speed or potential energy. Conversely compare that to a craft in an eccentric orbit, as it travels away from the body it isn't losing energy as the kinetic energy is reversibly converted to potential.
If you do not believe me then look at other sources:
"In astrodynamics and rocketry, gravity loss is a measure of the loss in the net performance of a rocket while it is thrusting in a gravitational field. In other words, it is the cost of having to hold the rocket up in a gravity field.

Gravity losses depend on the time over which thrust is applied as well the direction the thrust is applied in." from https://en.wikipedia.org/wiki/Gravity_loss
"In the coast phase the gravity loss is zero." from page 7 of https://web.stanford.edu/~cantwell/AA284A_Course_Material/Karabeyoglu%20AA%20284A%20Lectures/AA284a_Lecture7_Gravity_Loss.pdf

**Comment by tavert** [comment]
> Conversely compare that to a craft in an eccentric orbit, as it travels away from the body it isn't losing energy as the kinetic energy is reversibly converted to potential.

It doesn't lose energy, but it does lose velocity. How do you want to measure gravity loss? If it's in terms of energy then sure it can be zero for a coasting craft in an eccentric orbit. But if it's in terms of speed, it should directly follow what I said 10 years ago

current speed = initial orbital speed + delta-v expended - gravity losses - drag losses - steering losses

Then gravity losses should keep accounting for gravity minus the centripetal term from horizontal velocity, unchanging in a circular orbit but variable otherwise. Gravity losses would go up as you ascend towards apoapsis in an eccentric orbit and slow down, then gravity losses go back down as you descend towards periapsis and speed up.
