### ISSUE TITLE
MechJeb should not control ship when no RemoteTech/CommNet signal or RP-0 avionics (toggleable)

### ISSUE THREAD

**Issue by MOARdV** [MuMech/MechJeb2#382]
The current development of RemoteTech allows "Sanctioned Pilots" to be added to the RT control queue.  The implementation of this ability requires the caller to register an OnFlyByWire method with RT.  Essentially, to disable flight controls, RT has a post-OnFlyByWire method that neutralizes the FlightCtrlState changes when the vessel in question is uncontrolled.  After nulling out the state, RT calls sanctioned autopilots.

It's trivial to write a bridge DLL to add MechJeb to the sanctioned pilots list, but it requires MechJebCore.OnFlyByWire to be made public (it's private right now).  It does mean that MJ's OnFlyByWire would be called twice per update, although the first instance's effects will be cancelled out - so, a better solution would also be to allow an external caller to ask MechJebCore not to inject its OnFlyByWire method into the vessel.OnFlyByWire stream.  I don't know how feasible the latter actually is, or if the MJ team is willing to accept that sort of change.  I can implement the private -> public change easily, and I can research the latter if it's acceptable, but I wanted to get a discussion on them before I generate pull requests.

**Comment by Falkvinge** [comment]
Allow me to also add my interest in this. Since MechJeb is running locally on the vessel, there should reasonably be no signal delay from MechJeb to the vessel controls, BUT there should be a signal delay from the control center to execute MechJeb procedures or set MechJeb states (such as "land somewhere", "vector-surface-up", "begin docking", et cetera). Is there any hope of this happening?

**Comment by sarbian** [comment]
With the current way MJ is coded that would be quite complex. I might have a look at doing it when redoing the whole UI code for KSP 1.1.
I guess some kind of message bus would do the trick and if done right I could also interface it with the 1.1 "light RT"

But not before the 1.1 UI integration since it will require a large code rewrite anyway.

**Comment by Falkvinge** [comment]
It may be worth asking the RemoteTech authors for such a message bus - sort of a "return this cookie to me after the signal delay, if and only if a connection exists"? That would enable solving the problem in the general case.

**Comment by TheBlackTower** [comment]
here's an idea... since mechjeb interface comes from an object when attached to the ship, you could block its interface by blocking the original mechjeb part and replacing it with some other part, since its your part then you could put your interface and all you would have to do its unban mechjeb but imput a delay in commands and then send the cookie to mech

**Comment by leftler** [comment]
@MOARdV one thing you could try instead of working on the expectation of `OnFlyByWire` being made public you could override `Drive` on the relevant controller classes. I have made a similar workaround that overrides `Drive` on `MechJebModuleThrustController` and `MechJebModuleAttitudeController` over at https://github.com/leftler/RemoteTechMechJebBridge

        public RemoteTechMechJebBridgeModuleMechJebModuleThrustController(MechJebCore core) : base(core)
        {
            priority = 800;
            driveDelegate = DriveFromRemoteTech;

            //We must remove the stock MechJebModuleAttitudeController if it already has been added and add it to the blacklist.
            var originalModules = core.GetComputerModules<MechJebModuleThrustController>();
            foreach (var originalModule in originalModules)
            {
                if (originalModule.GetType() == typeof(MechJebModuleThrustController))
                {
                    core.RemoveComputerModule(originalModule);
                }
            }
            if (!core.blacklist.Contains(typeof (MechJebModuleThrustController).Name))
            {
                core.blacklist += typeof (MechJebModuleThrustController).Name;
            }
        }

        public override void OnLoad(ConfigNode local, ConfigNode type, ConfigNode global)
        {
            base.OnLoad(local, type, global);
            AddPilot();
        }

        private void AddPilot()
        {
            if (vessel != null)
            {
                //This method is safe to call multiple times, it the same delegate is added it does not add it a 2nd time.
                RemoteTech.API.API.AddSanctionedPilot(vessel.id, driveDelegate);
            }
        }

        public override void Drive(FlightCtrlState s)
        {
            //Do noting
        }

        private void DriveFromRemoteTech(FlightCtrlState s)
        {
            if(!enabled || core != vessel.GetMasterMechJeb() || core.DeactivateControl)
                return;

            base.Drive(s);

            core.CheckFlightCtrlState(s);
        }

Now, this is just my first pokes at this, and I doubt I will ever release a finished version of this but if you want to take the idea and run with it I would be more than happy to let you.

**Comment by sarbian** [comment]
You sure love complex solution. 
Sorry but anything that plays with the modules list like that is a no go for me.

**Comment by leftler** [comment]
Like I said, it is a hack and I have no intention of turning it in to a formal mod. But I did get some ideas last night while I was trying to sleep that may provide a better solution.

**Comment by leftler** [comment]
Slightly off topic, but related to what I was looking in to, is there a specific reason `GetComputerModule<T>()` uses the unordered list and not a ordered one? If it used the ordered one it would make the calls deterministic (as long as the priority is different) in the event two of the same module are registered.

**Comment by sarbian** [comment]
Because having 2 of the same module is not something I want to see or deal with...

**Comment by MOARdV** [comment]
I forgot I opened this issue.  Anyway, I am not working on this.  If someone else wants to pick it up, cool.  Otherwise, I can close it.

**Comment by lamont-granquist** [comment]
Constraining this issue to just disabling MJ when out of range and/or the ship has no avionics in RP-0.  Those should be independently toggleable (I would only care about making certain I have enough avionics to control the craft).  Signal delay would be vastly harder and I think I'll just assert that will never happen and is out of scope (speaking personally that would be months of work and as I never play with signal delay and find it pointlessly frustrating, I have zero interest in spending any time working on it -- sounds like sarbian is in roughly the same camp...).

**Comment by lamont-granquist** [comment]
This is actually done on the MechJeb side.

See https://github.com/KSP-RO/RP-0/issues/497 for the RP-0 bug to implement it on that side.

Other consumers should look in that issue for a pointer to the API to use.
