### ISSUE TITLE
ascent guidance doesnt complete orbit

### ISSUE THREAD

**Issue by superduck1** [MuMech/MechJeb2#525]
In older version of mechjeb and ksp i had no problem using ascent guidance it would complete the set oribt.

Now it just seems to continue firing my engines until the run out
I am Running Kerbal Space Program - 0.90.0.705, windows 7 32
I have the latest versions of Chatter mod, and Mechjeb
My system is
Intel quad core 2.66ghz
4 gig Ram
windows 7
Radeon HD 5700

Ive Tried in Career and Sandbox mode, 32, and 64 bit installs
and all have same results, Also Orbit Inclination seems to be off as well
Ive tried Controlling from command pod and also from Mechjeb Ar202 and doesnt seem to change anything as well. Also Tried on different ships and same problem
here of some screenshots of what i Mean
http://postimg.org/image/hj21te239/full/

http://postimg.org/image/4sxtgau51/full/

**Comment by sarbian** [comment]
Could you try with the last dev build ?
http://jenkins.mumech.com/job/MechJeb2/lastSuccessfulBuild/artifact/jenkins-MechJeb2-388/MechJeb2-2.4.2.0-388.zip 
There was quite a few change since the last release. 

If it still does not work can you post the KSP_Data/output_log.txt (for 32bit) somewhere ?

**Comment by superduck1** [comment]
That Did it!
Thats a million, that was frustrating the hell out of me. Thanks from the speedy rely and the great help
