### ISSUE TITLE
Request: Establish new orbit in Maneuver planner

### ISSUE THREAD

**Issue by tivec** [MuMech/MechJeb2#584]
I like the functionality of the Rendezvous Planner, where you can quickly establish two maneuver nodes to make a new circular orbit. Would it be possible to have this functionality in the Maneuver Planner window? Right now, I target some arbitrary vessel around the same body and use the Rendezvous Planner for this.

**Comment by ichaleynbin** [comment]
I may be misunderstanding what you mean here, but I'm fairly sure this functionality has been built in since KSP was in alpha. 

![image](https://cloud.githubusercontent.com/assets/2417892/7602246/1ec28e20-f8f0-11e4-8721-8764e6c51d4d.png)

Schedule burn for new Apoapsis 

![image](https://cloud.githubusercontent.com/assets/2417892/7602253/45a7e396-f8f0-11e4-8413-0c5daa8443c9.png)

Schedule burn for circularization at new apoapsis 

![image](https://cloud.githubusercontent.com/assets/2417892/7602259/58413a0c-f8f0-11e4-8591-c3fbb966e5e3.png)

Execute all nodes. 

Note: Any within tolerance burn errors (for example, instead of reaching 1.2 million meters, you reach 1.1967 million meters) will stack up the more nodes you stack. If you attempt to rendezvous by scheduling 4 or 5 burns at once and then executing them all one after another, you will probably miss quite badly. Once you schedule a burn, you have set a vector and a time for your burn, and it is no longer a (example) command to circularize, but a command to burn for so long in a given direction. 

What I mean by this is that if you set your tolerance to 1 m/s, schedule a new apoapsis burn and a circularization burn, you will NOT end up in a circular orbit. If you had executed the apoapsis change burn perfectly, then the circularization burn would have circularized your orbit. But 1 m/s tolerance means you did not execute the apoapsis change burn perfectly, and your apoapsis is not what was predicted, so you need a different vector for your circularization burn than the one you scheduled.

**Comment by ichaleynbin** [comment]
![image](https://cloud.githubusercontent.com/assets/2417892/7602396/281e757c-f8f2-11e4-8ce2-aaeb17138b26.png)
This is what I mean by that. When I told mechjeb to schedule a circularization burn, it scheduled a burn in 1h and 29 seconds, with 132.62 m/s in the prograde direction, 0.015 m/s in the radial out direction, and 3.86 m/s in the normal direction, which when you use the 3d pythagorean  theorem, d = sqrt(a^2 + b^2 + c^2), you get 132.6 m/s total since the prograde component is very dominant. Once the burn is scheduled, it is no longer a "circularization burn" per se, but a burn which will bring you to circular IFF (sic) your first burn is executed properly. 

To wit, I recommend against scheduling more than 2 burns, 3 at maximum if the resulting orbit does not have to be very precise.

**Comment by futrtrubl** [comment]
Yup, misunderstanding ;']
Say you are given a desired orbit, inclination, LAN, periapsis etc, and you are in some different orbit. He wants MJ to be able to calculate and execute the required burns to get into that desired orbit. Like the optimum two burn calculator in KSPTOT.

**Comment by ichaleynbin** [comment]
Such as for the "Launch an unmanned probe into a given orbit" missions? 

That functionality would be useful. I find myself using the built-in burn scheduler and/or maneuver node editor for these missions rather than the maneuver planner. In the meanwhile, scheduling burns one after another w/ the planner seems to solve the example issue, of wanting two nodes quickly scheduled to create a new circular orbit.

**Comment by futrtrubl** [comment]
Of course it can be done manually. He is asking if it can be done automatically. Just like rendezvous can be done manually but there is a module to do it automatically.

**Comment by ichaleynbin** [comment]
I guess my question is this, then. 

What is the actual functionality missing/being requested? "Establish new circular orbit at X"? "Establish new orbit with these parameters (including argument of periapsis, LAN, etc.)"?

**Comment by tivec** [comment]
The exact button found in the rendezvous planner, "Establish new orbit at ...", is what I asked for, but as @ichaleynbin said in the previous comment, it would be *great* to have something including argument of periapsis, LAN, and all those parameters as well :)

**Comment by jacksonj04** [comment]
Ah, that makes a lot more sense. I was initially confused too.

So, basically what you're after is a "new orbit" autopilot which won't try to schedule all the burns at once, but which will instead follow a similar pattern to rendezvous autopilot in that it will fix your inclination, apoapsis, periapsis, arguments etc all in the most sensible sequence?

In that case, :+1:, since it's often easy to get yourself roughly right manually, but fine-tuning it is a pain.

**Comment by ichaleynbin** [comment]
I agree, adding in the functionality to auto schedule a new burn **after** the current burn is completed would add a lot of precision which cannot be achieved currently without scheduling burns one at a time.

**Comment by tivec** [comment]
Yes, that is exactly what I want:) extra parameters such as inclination etc
are just a bonus.

**Comment by lamont-granquist** [comment]
#1058
