### ISSUE TITLE
Ascent AP to hold attitude during staging

### ISSUE THREAD

**Issue by asmi84** [MuMech/MechJeb2#72]
The basic problem is that vessel need to be stable during strapons jettison otherwise they can recontact with the rest of the vessel. Sounds like one more checkbox :)

**Comment by lamont-granquist** [comment]
This issue is being closed because it appears to be more of an issue with rocket design or physics that is not directly related to MechJeb issues or bugs and is more of a general KSP issue.  It may also be a better question to answer on [the forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/154834-14x-anatid-robotics-mumech-mechjeb-autopilot-274-23-september-2018/)
