### ISSUE TITLE
Landing guidance is only acting like "Land Somewhere"

### ISSUE THREAD

**Issue by FireFaced** [MuMech/MechJeb2#722]
I have a rocket I'm trying to do a boostback with, and the landing guidance refuses to navigate it. It just acts like the Land Somewhere option. I've tried it with targeting my barge and the KSC pad before, but the Land at Target still just landed where the rocket was headed.
[Log](https://www.dropbox.com/s/w5x0fakekcs9268/output_log.txt?dl=0)

**Comment by BloodyRain2k** [comment]
Was your trajectory somewhere close to the target?
Because as I remember it did MJ refuse to do a 180 to land at a target 
site and instead defaults to anywhere in that case.
The definition of "180" included back when I last messed with it burning 
away 1 or more km/s to not overshoot.

So unless you were already trajecting near the target would I guess that 
this is the reason it does 'anywhere' instead.

**Comment by FireFaced** [comment]
@BloodyRain2k I've tried it with a trajectory near the target, same issue.

**Comment by FireFaced** [comment]
Tried with the latest version of MJ, same issue. I might take a look through the source.

**Comment by lamont-granquist** [comment]
dup of #1052.

boostback burns to RTLS are better done with kOS scripts
