### ISSUE TITLE
Translatron with "Kill HS" is unable to control heavy vessel with little gimbal torque.

### ISSUE THREAD

**Issue by versvisa** [MuMech/MechJeb2#733]
Using Translatron in "KEEP VERT" mode with "Kill HS" on a very heavy vessel (500mT) with little gimbal torque creates an unstable oscillation. The controller manages to momentarily kill the horizontal velocity but the vessel is still pitched at that point and continues to accelerate in the opposite direction.

Suggested fix: Create an option to allow the user to change how aggressively the Translatron wants to decelerate, i.e. the gain coefficient between horizontal velocity and pitch.

**Comment by BloodyRain2k** [comment]
Oversteering and not pitching center ahead of time has been an issue 
with that thing since forever : (

I tried to fix it once, but just managed to make it sliiightly less bad, 
but it still sucked half the time...

I'd not really need an aggressively slider, just finally getting aware 
of when to counter.

**Comment by lamont-granquist** [comment]
this is likely a PID issue and probably needs to be recreated on the "HybridController" PID under the Attitude Adjustment menu.
