### ISSUE TITLE
Kerbal Alarm Clock and Mechjeb Do not play nice with Timewarp

### ISSUE THREAD

**Issue by Ruedii** [MuMech/MechJeb2#754]
MechJeb and Kerbal Alarm Clock do not respect each other's changes to time warp.

This should probably be addressed on both ends, as well as making some sort of way that other mods can universally handle time warp so they respect each other's priorities.

I will be reporting this on both Mechjeb and Kerbal Alarm Clock's issue threads, because it is with both of them, and they likely conflict with other mods as well on this..

**Comment by nickearl** [comment]
@sarbian The fix for this in dev build 604 and newer also kicks in when the game itself changes the warp speed (eg, when passing through certain altitudes that limit warp such as 120K over Kerbin), which can lead to MechJeb missing a maneuver node.  May want to adjust the logic to exclude this kind of change from pausing MJ's warp controller or give an option to turn this functionality off.
