### ISSUE TITLE
Mechjeb 2.5.8.0 not executing burns

### ISSUE THREAD

**Issue by piguy54** [MuMech/MechJeb2#769]
Using Interstellar mod, mechjeb not executing burns, issues I've had :

Ascent assistance - ascends to coast point, turns to circulization burn direction, warps to a few seconds before burn, misses the burn and never applies throttle.
Circulization maneuver - turns in direction of burn, warps to a few seconds before burn, never throttles up and misses burn.
Hohmann transfer - Starts burning WAY to early to WAY to late, either way misses intercept completely.

I have attached save with 2 ships in orbit and the craft I'm using, tested with both the mechjeb pod and smaller part.

[save.zip](https://github.com/MuMech/MechJeb2/files/344931/save.zip)

**Comment by sarbian** [comment]
Thanks for sharing the save but I would rather see a log before looking into it more.

**Comment by piguy54** [comment]
Sure, not sure how to get you a log though.

**Comment by piguy54** [comment]
stupid question, see attached, interesting lines on 101516
[output_log.txt](https://github.com/MuMech/MechJeb2/files/344960/output_log.txt)

**Comment by piguy54** [comment]
Just replicated and found the same debug lines all the way through the maneuver.

**Comment by sarbian** [comment]
I am afraid I can not help much with that. The upgraded Interstellar engine has value that do not makes sense (maxFuelFlow = 0) so MJ can not calculate the stages delatV. I could change some of the math to use the same thing as KER do but I don't want to do that just because those engine report stupid values.

I added some code in the new dev build that prevents the exception when such engine are found so you will have the proper stats (and node execution) for stages that do not uses those engines.

**Comment by sarbian** [comment]
I had an  other idea and the new dev build now properly show the dv for those engine.

**Comment by piguy54** [comment]
What a boss, thank you
