### ISSUE TITLE
Ascend Guidiance Orbit Inclination acting strange

### ISSUE THREAD

**Issue by Lofwyrger** [MuMech/MechJeb2#782]
Just tried to start a set of Mapsat Satelites to 87° Inclination Orbit, but ascend guidiance brings me up to a 92.259° inclination.
Using FAR and KScale64, no idea if that matters.

**Comment by lamont-granquist** [comment]
Presumably you're using https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/629/ or later?

And how does it behave on https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/626/ or earlier?

**Comment by superdavekerman** [comment]
I just tested build 629 and a polar -90 inclination worked fine.  The moon launch I tested was ok, but had a relative inclination of 9.75 when it was done (but better than prior build.)  These tests were from KSC in RSS.

**Comment by lamont-granquist** [comment]
yeah i don't think the autopilot knows how to properly 'lead' a moon launch and definitely has no ability to jog south so its going to be off.   i think you can likely do better than that by tweaking the config setting and by manually jogging a bit south first.   for any inclination above KSC's latitude it should work pretty well in RSS.  where it gets really messy is when the body gets smaller and the TWR gets higher.  inclination guidance on gilly in stock can be amusing without some severe throttle limiting.  i tested in stock on kerbin, though, at a variety of inclinations, and included testing on the mun and it worked pretty well for me -- kscale64 should work better than stock since its bigger.

**Comment by kunnis** [comment]
I've submitted a PR that should resolve this.

**Comment by lamont-granquist** [comment]
@sarbian can probably close this

**Comment by Cub66346** [comment]
Landing guidance menu is gone and none of the menus read that I have a Target selected as in ships or planits

**Comment by lamont-granquist** [comment]
This was probably fixed ages ago.  For RSS/RO users, they should use PVG guidance in #1061 when it lands -- Soon(tm).
