### ISSUE TITLE
Windows "locked" settings not saved

### ISSUE THREAD

**Issue by tenshi99** [MuMech/MechJeb2#819]
Windows "locked" settings not saved. Also turn on "Use only the titlebar for window dragging" does nothing.

**Comment by BloodyRain2k** [comment]
Yeah I've noticed too that some past update broke the titlebar only dragging I've added somewhen.

Someone added some handling for locked windows and completely disabled the titlebar only dragging in the process. I tried fixing it myself but since I don't even know how that locking works did I likely only break that in turn which is why I didn't submit a fix yet.

I was hoping that whoever added that window locking thing would eventually try fixing the titlebar dragging : /

**Comment by sarbian** [comment]
I did not notice the part about the titlebar. Fixed now
