### ISSUE TITLE
Documentation .....

### ISSUE THREAD

**Issue by FrostbittenKing** [MuMech/MechJeb2#854]
Either I'm blind, or there is _zero_ explanation, what the input fields right of the Launch to rendevous and Launch into plane of target do. This part just isn't documented on the wiki. What do these values mean. Might have to do with the Linux version but I can't "decipher" those icons right of the fields. Might be degree, but whatever. After selecting a target (an asteroid). Is this feature maybe broken?

**Comment by kunnis** [comment]
It's not documented, but that's the phasing angle, to know how early/late to launch to arrive at the correct time.  Basically that value says how long it takes for you to reach orbit.

For launching into plane, it controls how far ahead of your target plane you launch, so you hit the target inclination at just the right time.

For launch to rendezvous, it basically says how far back your target should be before launching.

In general, when you fly manually, and you watch for the exact spot over kerbin something needs to be for you to be able to launch and meet it?  You're doing a phase calculation right there.

**Comment by FrostbittenKing** [comment]
Oh, I get it. Is there any way to use that for launching into the right plane to capture an asteroid? I selected some asteroid, but it seems to not work for objects that enter the SOI on a later date. Does the game provide you with the necessary information to launch at the correct timeframe to get into the correct plane for objects entering the SOI? The only way I found which more or less worked with +-1-2 degree, was eyeballing the plane by zooming in/out at the projected SOI. Is there any way to calculate that manually, so I can enter a launch date or something manually?

**Comment by kunnis** [comment]
Phase angle is tied with exactly how long your craft takes to get into orbit, and the phase angle is specific to the craft & altitude of orbit, your inclination, and your target's lan+inclination.  The inclinations only have a moderate impact on the values, so sometime you can work around it.

Now that I think about it, instead of phase angle, we should consider using time, and calculate the phase angle from the time... but oh well.  I'll figure out how to do that one day and add it as a feature.

One way to figure out your phase angle is to do a launch from kerbin.  After the ascent is complete & circularized, You can then revert to launch.  Press the launch into target plane button, and it should show you what the correct value should have been.  In theory.

I've done ascents where it's landed me less then 200m from my target once I got my phase angle correct.

**Comment by FrostbittenKing** [comment]
Yeah, I know that, but thats annoying as hell. About that using time, I thought about that for some time, after writing my questions. We know the phase angles and periods at Time 0.. what we would need is the global angle of KSC at Time Zero, after that, we can calculate an Exact Angle relative to Prograde / Retrograde of Kerbin, with that you could implement something like this:

- Project the Asteroid's path inside Kerbins SOI to Kerbin
- Calculate where this Projected line intersects with the equator
- From the position of KSC at Time Zero calculate a current time frame for the KSC to arrive at that intersection.
