### ISSUE TITLE
Missing Information/Manual

### ISSUE THREAD

**Issue by Krahazik** [MuMech/MechJeb2#999]
wiki.mechjeb.com drastically outdated and missing information.

Using MechJeb 2 version 2.7.0.0
KSP version 1.3.1.1891 
Windows 64it

As a result of a lack of information I have no idea if some of the issues I am having are a result of a mod bug, or incorect settings for the craft im flying. There are whole sections missing completely (Aircraft Autopilot window for example) and some sections are incomplete with settings missing. This leads to lots of questions and not sure where to post questions.

In Aircraft Autopilot under PID, what are those settings? What is "Kp", what is "i" and "d". How does the "VertSpeed" fields under PID effect "Vertical Speed Hold" if it effects that at all.
I have one aircraft where vertical speed hold fails completely and results in dratic and fata pitching ocillation. No idea why?

There are settings on the Assent Guidence window that have no informations. What is "Q"?
What are the force roll settings for?

With an aircraft, I had Autoland completely fail to make touchdown. Was doing good untill the point where it should have moved the craft to make contact with the runway but instead just hovered there untill the plane lift stalled and crashed.

**Comment by tekinozbek** [comment]
Good point, we should probably update the documentation. Both autopilot and autoland are fairly new components added in the last cycle, which is why the docs aren't updated yet to reflect the changes.

PID settings are unfortunately not universal (although they work fairly well for most stock aircraft, not all). To see the effects of changing the values of Kp, Ki and Kd parameters, see this graph: https://en.wikipedia.org/wiki/PID_controller#/media/File:PID_Compensation_Animated.gif (there's also more information in that Wikipedia article about what those parameters are and how they affect the controller).

The oscillation that you get when trying to hold vertical speed is because the PID parameters are not configured properly for your aircraft. Configuring the values properly, as you see in the gif I linked above, makes the oscillation go away and allows the aircraft to get a smooth transition between two different vertical speed rates.

Autoland depends on the autopilot component and therefore bad PID values will negatively affect autoland performance.

At some point, I'll look into the possibility of a self-adjusting PID controller for a better user experience.

As for your issues: I do know that hovering until stall used to be an issue when the approach speed was too high for landing, but a change that was merged recently should have fixed that issue (although it can only be found in the dev builds, it didn't make it to release on time).

Could you please attach the vehicle you were flying and give me the version number you have installed?
 Thanks.

**Comment by lamont-granquist** [comment]
https://github.com/MuMech/MechJeb2/wiki is starting to be updated.

best way to get updated docs, though, is to update them.  for something the side of mechjeb doing the doc work would be a full time job and nobody gets paid for this work.
